package simulations

import io.gatling.core.scenario.Simulation
import io.gatling.core.Predef._
import io.gatling.http.Predef._


/*
* The bearer token for below API is generated by logging to https://gorest.co.in/ using Github
*
* Once you login to above website you would get a bearer token
*
* */


class CheckResponseAndExtractData extends Simulation {
  val httpConf = http.baseUrl("https://gorest.co.in/")
    .header("Authorization",value = "Bearer 395d0049d1c794ec1232dadb5c645ee71c8e8bfdd40b51eb3142a90ea29897f9")

  val scn = scenario("Check Correlation and extract data")
    //First Call -Get All Users
    .exec(http("Get all Users Request").get("public-api/users")
      .check(jsonPath("$.data[0].id").saveAs("userId"))
      .check(status is 200))
    .pause(3)

    //Second API - Get a specific user on the basis of id
    .exec(http("Get Specific User Request").get("public-api/users/${userId}")
    .check(jsonPath("$.data.id").is("5298"))
    .check(jsonPath("$.data.name").is("Amish Bhattacharya")))

  setUp(scn.inject(atOnceUsers(1))).protocols(httpConf)
}
