package simulations

import io.gatling.core.scenario.Simulation
import io.gatling.core.Predef._
import io.gatling.core.structure.ChainBuilder
import io.gatling.http.Predef._


/*
* The bearer token for below API is generated by logging to https://gorest.co.in/ using Github
*
* Once you login to above website you would get a bearer token
*
* */

class DataFeederCSV extends Simulation {

  val httpConf = http.baseUrl("https://gorest.co.in/")
    .header("Authorization",value = "Bearer 395d0049d1c794ec1232dadb5c645ee71c8e8bfdd40b51eb3142a90ea29897f9")

  //circular,shuffle,random,queue
  val csvFeeder=csv("./src/test/resources/data/getUser.csv").circular

  def getUser():ChainBuilder={
    repeat(3) //Repeat Request thrice
    {
      feed(csvFeeder) // Feeder for the request
        .exec(http("Get single user request").get("public-api/users/${userid}")
          .check(jsonPath("$.data.name").is("${name}"))
          .check(status is 200))
          .pause(2)
    }
  }

  val scn=scenario("Data Feder scenario")
    .exec(getUser())

  setUp(scn.inject(atOnceUsers(1))).protocols(httpConf)

}
